### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by clhenrick** [clhenrick/am-i-rent-stabilized#13]
Here are some break points that need to be designed around, probably will also benefit to dry-ify some CSS.

#### Portrait View breakpoints:
- map slide give more margin to top
- fix address search slide
- fix font size for options
- more even spacing on last slide

#### Landscape View breakpoints:
- fix elements on slide 2 for address search 
- fix spacing / size of elements on calendar slide

#### Portrait View breakpoints:
* Q: What is the best way to detect mobile? max-width or min-width?
* 420px: 
  - solution: using max-width 420px

* Q: height varies a lot in mobile (eg: iPhone 4 vs. iPhone 6plus),
     should solution be to design multiple layouts based on mobile height?

#### Height based break points:
* 565px: 
  (small screens as well as landscape view on mobile)
  - bottom arrow crashes into text
  - last slide share icons disappear

* < 640px: on slide 2 the 'select borough' dropdown goes below window.

#### Width based break points:

* 980px nav bar lists crash into Title
  - solution: toggle hamburger icon

* 980px address input crashes into progress circles
  - solution: stack input & drop down

* 1100px: `<h1>` tags crash into language toggle
  - Q: how to balance this without stacking the text too much?
       make the font size smaller?

#### Width breakpoints:
* 980px: content crashes into side nav
  - fix by making flexible columns?

**Comment by clhenrick** [comment]
Most recent updates can be seen at http://clhenrick.io/am-i-rent-stabilized

**Comment by edwerd** [comment]
> Q: What is the best way to detect mobile? max-width or min-width?
For CSS you don't need to detect mobile you just need to set a breakpoint of less than 480 pixels. In JS check the size of the window instead of the device type

> Q: height varies a lot in mobile (eg: iPhone 4 vs. iPhone 6plus), should solution be to design multiple layouts based on mobile height?
You should really create layouts based on 100% height and use percentages to align accordingly. Ideally you only have 3 total break points, none of width account for height

> Q: how to balance this without stacking the text too much? make the font size smaller?
Make the font smaller. Use ems to determine fontsize 

This article by Trent Walton should be helpful overview.
http://trentwalton.com/2014/03/10/device-agnostic/

Kyle Schaeffer explain's responsive fonts here:
http://kyleschaeffer.com/development/css-font-size-em-vs-px-vs-pt-vs/

**Comment by clhenrick** [comment]
Thanks Ed, I understand the principles behind these responsive design recommendations and am implementing them (for example using `body { font-size: 62.5%; }` then the `em` units for the rest of the CSS). Think it will be easier to go over specifics in person next week. In the meantime I'll read those books you sent me :)

**Comment by clhenrick** [comment]
- [ ] fix position of form validation errors on medium screens
- [ ] fix typography on tablet portrait
- [ ] fix typography / layout on mobile landscape
