### ISSUE TITLE
find code / framework  to implement content translation toggle

### ISSUE THREAD

**Issue by clhenrick** [clhenrick/am-i-rent-stabilized#14]
ideas:
- translatewiki.net
- https://github.com/fnando/i18n-js
- ember js

**Comment by clhenrick** [comment]
reference #18

**Comment by hahla** [comment]
Just have the browser do it? https://support.google.com/chrome/answer/173424?hl=en

**Comment by clhenrick** [comment]
Google translate isn't perfect though, would rather make sure everything is
translated as accurately as possible.


-Chris L Henrick
-------------------------
MFA Candidate, Design & Technology
Parsons, The New School For Design

Cartographic Design Portfolio <http://chrishenrick.com> - Thesis Blog
<http://clhenrick.github.io/thesis-blog/> - MFA DT Blog
<https://chenrickmfadt.wordpress.com/>
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by hahla** [comment]
you should also make it work on IE 4 then

**Comment by clhenrick** [comment]
Lol

On Thursday, April 23, 2015, Michael Salmon <notifications@github.com>
wrote:

> you should also make it work on IE 4 then
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clhenrick/am-i-rent-stabilized/issues/14#issuecomment-95749586>
> .
>


-- 

-Chris L Henrick
-------------------------
MFA Candidate, Design & Technology
Parsons, The New School For Design

Cartographic Design Portfolio <http://chrishenrick.com> - Thesis Blog
<http://clhenrick.github.io/thesis-blog/> - MFA DT Blog
<https://chenrickmfadt.wordpress.com/>
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by jueyang** [comment]
Another way to do this is to jekyll-ify the site. Depends on how familiar you're with jekyll, though. See https://github.com/hotosm/learnosm. In particular:

https://github.com/hotosm/learnosm/blob/gh-pages/_layouts/default.html#L97 and 
https://github.com/hotosm/learnosm/blob/gh-pages/all-translation.json

**Comment by clhenrick** [comment]
*The easy solution for toggling between only three languages:*
```
cp -r *.html es/
cp -r *.html zh/
```
- then edit content of the files in `es/` and `zh/` respectively. 
- In future look into using something more fancy ;)
