### ISSUE TITLE
vertically size & distribute elements evenly on main page

### ISSUE THREAD

**Issue by clhenrick** [clhenrick/am-i-rent-stabilized#24]
For example with short screens on mobile devices the bottom nav arrow crashes into elements above it:
![screen shot 2015-05-23 at 8 32 32 pm](https://cloud.githubusercontent.com/assets/161748/7786205/004f87b0-018b-11e5-9837-e85977c7bdd0.png)

**Comment by clhenrick** [comment]
ideas @edwerd or @jueyang?

**Comment by clhenrick** [comment]
- one option would be to ditch the larger building graphic & use a 2 column layout on the landing page.   
- another could be to add a swipe interaction that functions similarly to scroll wheel for touch screens and not show the bottom arrow for shorter screens on mobile

**Comment by jueyang** [comment]
What device has such a squarish dimension? You're already telling the user to rotate their phones when it's in landscape, which is a good solution.

**Comment by clhenrick** [comment]
@jueyang think it's an issue with the iphone4

**Comment by jueyang** [comment]
- make the font smaller (seriously, the es/zh versions look fine in squarish views)

**Comment by clhenrick** [comment]
true


-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

Cartographic Design Portfolio <http://chrishenrick.com> - Thesis Blog
<http://clhenrick.github.io/thesis-blog/> - MFA DT Blog
<https://chenrickmfadt.wordpress.com/>
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells
