### ISSUE TITLE
Link address search to Rent Logic building profile

### ISSUE THREAD

**Issue by clhenrick** [clhenrick/am-i-rent-stabilized#43]
Sample mocks for providing link at the end of search:

<img width="1440" alt="amirentstabilized-v1" src="https://cloud.githubusercontent.com/assets/161748/19843355/e32708aa-9ede-11e6-93e6-b5afefc050a8.png">

<img width="1440" alt="amirentstabilized-v2" src="https://cloud.githubusercontent.com/assets/161748/19843356/e327215a-9ede-11e6-9576-dccb76ac0bbc.png">

Linking to the building page would have to be done by BIN, (see [BIN to URL CSV](https://chenrick.carto.com/tables/bin_bbl_url)), so would need to grab the BIN from the GeoClient API.

**Comment by BersnardC** [comment]
I'm trying CARTO api.  
https://chenrick.carto.com:443/api/v2/sql?q=select * from public.bin_bbl_url where cartodb_id=291
where the ubication of your maps is returned like json in: https://rentlogic.com/building/50-west-street-manhattan.

**Comment by BersnardC** [comment]
This API is beautifull

**Comment by clhenrick** [comment]
Resolved in 58ac9d2
