### ISSUE TITLE
Use new GeoSearch API

### ISSUE THREAD

**Issue by allthesignals** [clhenrick/am-i-rent-stabilized#49]
Hello! First of all, thank you for creating and maintaining this awesome tool. I just used it myself. 

For what it's worth, I think we can improve the geocoding experience by using the new [GeoSearch API](http://geosearch-docs.planninglabs.nyc/) that my team at DCP released. It is an autocomplete API like Google Maps (each keystroke is a new request to find possible matches). All suggested matches return a BBL, which can be used as a lookup in PLUTO. Currently, _GeoSupport's_ API requires an additional step of selecting borough, and I think autocomplete is an overall better user experience.

Our team uses our new API in several in-production applications. 

Thanks for your time, and if I can help, let me know! Happy to pull request.

**Comment by clhenrick** [comment]
@allthesignals my apologies for just getting back to you now about this a month later! 

It would be great to incorporate the GeoSearch API that DCP has released. I agree that having autocomplete would be a much better UX than manually selecting the Borough name from a dropdown.

Please feel free to submit a PR if you are still interested!

**Comment by clhenrick** [comment]
implemented in #58!

**Comment by allthesignals** [comment]
@clhenrick awesome!
