### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by clhenrick** [clhenrick/am-i-rent-stabilized#5]

**Comment by clhenrick** [comment]
- [ ] Make the start button really prominent
- [ ] Make the text field / menu / button larger and full-width
- [ ] Don't use a search field for the address
- [ ] change the Okay! button to "Search" or "Check My Status" (something with a verb)
- [ ] don't use a circle on the results screen, as it cuts off text

**Comment by ebrelsford** [comment]
I think you should get pushed to the next/previous slide when you start scrolling, [like this for example](http://codepen.io/bassta/pen/kDvmC).

**Comment by clhenrick** [comment]
@ebrelsford I completely agree! This will make it more mobile friendly as well. Thanks!
