### ISSUE TITLE
Told you're not stabilized if you Don't Enter Borough

### ISSUE THREAD

**Issue by talos** [clhenrick/am-i-rent-stabilized#9]
If you put in your address but leave "Select Your Borough" blank, the information never loads, and no error is shown -- the app instead shows the loading spinner forever.

**Comment by clhenrick** [comment]
thanks @talos for pointing this out!

**Comment by talos** [comment]
Correction: it was stuck on loading spinner because of Firefox's Privacy Badger extension blocking the cross-site request to api.cityofnewyork.us.

However, there is still an issue if you don't enter the borough -- instead of telling you you need to specify, it erroneously says your building is probably not stabilized.

**Comment by clhenrick** [comment]
@talos thanks, noted.

**Comment by talos** [comment]
:+1:
